### ISSUE TITLE
[C++ client] Deadletter queue functionality

### ISSUE THREAD

**Issue by frejonb** [apache/pulsar-client-cpp#114]
Is anyone working on porting DLQ from the Java client to Cpp https://github.com/apache/pulsar/pull/2508? I'd like to help/contribute.

I'm thinking on the following API
```c++
Client client("pulsar://localhost:6650");

Consumer consumer;
ConsumerConfiguration config;
config.setMaxRedeliverCount(10);
config.setDeadLetterTopic("my-dlq-topic");

Result result = client.subscribe("persistent://prop/r1/ns1/my-topic", "consumer-1", config, consumer);
```

**Comment by shibd** [comment]
Related: https://github.com/apache/pulsar-client-cpp/issues/77

I will start working on this. @tisonkun Please assign it to me.

**Comment by tisonkun** [comment]
@shibd assigned. Go ahead!
