### ISSUE TITLE
batch receive in cpp consumer client

### ISSUE THREAD

**Issue by lalit-g-deepr** [apache/pulsar-client-cpp#178]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

I am writing application which is using apache pulsar for server to server communication. It would be easy if there is interface to receive messages from topics in batch as it is available in java client library. This way callback calls would be minimize and most of high throughput applications requires batching also.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Moved to the Pulsar C++ client repository.

**Comment by merlimat** [comment]
@lalit-g-deepr Keep in mind that the cpp client is already "efficient" as it receives the messages in batches. The batch receive only changes the style in which the messages are passed to the application, though not the throughput performance.

**Comment by lalit-g-deepr** [comment]
Ok, but it is helpful in cases when someone wants to batch process them. One needs to run iteration loop again and again. First they gets unbatched internally then gets rebatched by the application. It can cause high cpu consumption in high throughput cases.

**Comment by BewareMyPower** [comment]
This API is already added in https://github.com/apache/pulsar-client-cpp/pull/21.

**Comment by lalit-g-deepr** [comment]
Thanks @BewareMyPower. I checked the cpp client lib, it is there. I am closing this PR. I was looking into main [repo]([pulsar](https://github.com/apache/pulsar/tree/v2.11.0)/[pulsar-client-cpp](https://github.com/apache/pulsar/tree/v2.11.0/pulsar-client-cpp)/[include](https://github.com/apache/pulsar/tree/v2.11.0/pulsar-client-cpp/include)/[pulsar](https://github.com/apache/pulsar/tree/v2.11.0/pulsar-client-cpp/include/pulsar)/Consumer.h) where this interface is not available. I was not aware of moved client library. Please delete/update the pulsar-client-cpp from main whichever is applicable.
