### ISSUE TITLE
[Bug] subscribewithregex not working for non-persistence topic. or I need to switch it on from configuration.

### ISSUE THREAD

**Issue by lalit-g-deepr** [apache/pulsar-client-cpp#204]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

pulsar server 2.10.0 
pulsar-client-cpp 3.1.1
os redhat 8

### Minimal reproduce step

1. create non persistence producer
2. create consumer and use subscribeWithRegex 

I have used this on consumer side

consumer_config.setReceiverQueueSize(1000);
consumer_config.setAckGroupingTimeMs(5);
consumer_config.setAckGroupingMaxSize(60);
    
pulsar::BatchReceivePolicy policy(1000, -1,200);
m_Config.setBatchReceivePolicy(policy);
    
    

std::string regex_pattern_sub = "non-persistent://public/default/.*";
auto res = m_Client->subscribeWithRegex(regex_pattern_sub, sub_name, m_Config, m_Consumer);

### What did you expect to see?

I expect regex should work for non persistent topic also as it is shown in documentation.

### What did you see instead?

I don't see any coming messages

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Fixed by https://github.com/apache/pulsar-client-cpp/pull/207.
