### ISSUE TITLE
the C++ clients don’t have isClosed() method like the java client does for testing connection with pulsar server. Can is it implemented for C++ client?

### ISSUE THREAD

**Issue by lalit-g-deepr** [apache/pulsar-client-cpp#205]

**Comment by BewareMyPower** [comment]
It's not hard to implement. But I'm wondering in which case would you like to test the connection on a `Client` instance instead of a producer or consumer? The C++ client has `isConnected` methods for `Producer`, `Consumer` and `Reader`.

**Comment by lalit-g-deepr** [comment]
@BewareMyPower I am writing API for basic operation for producer consumers. I want that user can check connection without creating producer or consumer. After making connection with pulsar client if connection is not proper they don't need to create producer or consumer. Right now I am getting this functionality by creating dummy producer on test topic. Having this method would save creation of dummy resources.

**Comment by lalit-g-deepr** [comment]
ok @BewareMyPower got your point. Closing the request. Thanks for taking time out.
