### ISSUE TITLE
[Bug][KeySharedPolicy] bug where KeySharedPolicy::setStickyRanges duplicated ranges.

### ISSUE THREAD

**Issue by hyperevo** [apache/pulsar-client-cpp#241]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

OS: 5.10.157-1-MANJARO #1 SMP PREEMPT Fri Dec 2 21:02:47 UTC 2022 x86_64 GNU/Linux
Pulsar version: 3.2.0-pre

### Minimal reproduce step

Run the following unit test:

```
TEST_F(KeySharedPolicyTest, testStickyConsumerExpected) {
    // Test whether the saved range vector is as expected
    KeySharedPolicy ksp;
    ksp.setStickyRanges({StickyRange(0, 300), StickyRange(400, 500)});

    std::vector<std::pair<int, int>> expectedStickyRange {{0, 300}, {400, 500}};
    ASSERT_EQ(ksp.getStickyRanges(),expectedStickyRange);
}
```

### What did you expect to see?

I expect ksp->ranges to be a vector of the form { (0, 300), (400, 500) }

### What did you see instead?

I see a vector of the form { (0, 300), (400, 500), (0, 300), (400, 500) }. 

### Anything else?

The cause is that this for loop is nested when it shouldn't be. https://github.com/apache/pulsar-client-cpp/blob/86d66bdb09bdb596a2a5c25b0a09f3d0182d683e/lib/KeySharedPolicy.cc#L68

I will make a fix and add some tests and put it in a pr.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Fixed by https://github.com/apache/pulsar-client-cpp/pull/242
