### ISSUE TITLE
[Bug] Exception could be thrown when creating producers or consumers with Windows debug library

### ISSUE THREAD

**Issue by licj520** [apache/pulsar-client-cpp#259]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

3.2.0

### Minimal reproduce step

Client client("pulsar://ip:6650");
Producer producer;
Result result = client.createProducer("persistent://public/default/my-topic", producer);

### What did you expect to see?

![image](https://user-images.githubusercontent.com/105142798/234741103-a005028e-3ed8-48e3-958b-d78f66222a4b.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/105142798/234741422-17165bd9-883d-4e09-87b8-e5fc3a7f63a6.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by BewareMyPower** [comment]
Where did you download the debug library? If you built from source, please provide the commands you used.

**Comment by licj520** [comment]
> Where did you download the debug library? If you built from source, please provide the commands you used.

With vcpkg, run that commands
 
cmake \
 -B ./build \
 -A x64 \
 -DBUILD_TESTS=OFF \
 -DVCPKG_TRIPLET=x64-windows \
 -DCMAKE_BUILD_TYPE=Debug\
 -S .
cmake --build ./build --config Debug

**Comment by BewareMyPower** [comment]
Could you try the `x64-windows-static` triplet? I've built the debug libraries before and it worked well. Could you try these libraries?

[win-debug.zip](https://github.com/apache/pulsar-client-cpp/files/11352991/win-debug.zip)
