### ISSUE TITLE
[Bug] pulsar::InitialPositionEarliest Not effective

### ISSUE THREAD

**Issue by licj520** [apache/pulsar-client-cpp#260]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

3.2.0-pre

### Minimal reproduce step

Consumer consumer;
ConsumerConfiguration config;
config.setMessageListener(listener);
config.setSubscriptionInitialPosition(pulsar::InitialPositionEarliest);

### What did you expect to see?

After restarting, it can be received from the beginning

### What did you see instead?

Start spending from the Latest after restarting

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by BewareMyPower** [comment]
Could you add a code example to reproduce this issue? From my experience, mostly it's because you have already acknowledged a message. This configuration only works when the subscription has not been created and acknowledged.

**Comment by licj520** [comment]
> Could you add a code example to reproduce this issue? From my experience, mostly it's because you have already acknowledged a message. This configuration only works when the subscription has not been created and acknowledged.

ok , been acknowledged. Is there a way to consume again？

**Comment by BewareMyPower** [comment]
You can use the `Consumer::seek` API to see to a position that is represented by a `MessageId`.
