### ISSUE TITLE
[Bug] getSchemaInfoAsync is not honoring the PulsarClient timeout

### ISSUE THREAD

**Issue by armanjupriya-er** [apache/pulsar-client-cpp#357]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

Pulsar Client CPP version: 3.3

### Minimal reproduce step

getSchemaInfoAsync is not honoring the PulsarClient timeout and is not timing out.

### What did you expect to see?

Currently, we are having getSchemaInfoAsync method which gives the schema version asynchronously. We need a method to get the schema version synchronously and which will honor the pulsar client timeout. 

### What did you see instead?

getSchemaInfoAsync is not honoring the PulsarClient timeout and is not timing out.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by BewareMyPower** [comment]
It needs some refactoring to add a test because the operation timeout is configured by seconds, not milliseconds. I'm going to work on this issue next week.
