### ISSUE TITLE
[Feature Request] Expose get/setListenerName in the C API

### ISSUE THREAD

**Issue by roryschadler** [apache/pulsar-client-cpp#369]
https://github.com/apache/pulsar-client-cpp/blob/27cba3e7d154f97e01911cd5de2cc0d4eaf2ef50/lib/c/c_ClientConfiguration.cc doesn't seem to expose `getListenerName` and `setListenerName` from https://github.com/apache/pulsar-client-cpp/blob/27cba3e7d154f97e01911cd5de2cc0d4eaf2ef50/include/pulsar/ClientConfiguration.h#L270-L280 That prevents the Node.js binding from exposing it (see related issue https://github.com/apache/pulsar-client-node/issues/214), as it relies on the C API.

I'm not an expert, but at first glance this doesn't seem like a ton of work. I'd be willing to give it a shot.

**Comment by BewareMyPower** [comment]
Yes. It should be easy. If you want to try this feature, you can take a look at the previous PRs that add new C APIs. https://github.com/apache/pulsar-client-cpp/commits/main/lib/c

**Comment by roryschadler** [comment]
Thanks! Opened a PR: https://github.com/apache/pulsar-client-cpp/pull/370
