### ISSUE TITLE
[Bug] Inclusive start message Id not work when reader reads from latest msg id

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar-client-cpp#385]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

9ffd2ef45f87e52745d3baad454aae081f035507

### Minimal reproduce step

```
    Client client(serviceUrl);

    const std::string topic = "test-seek-latest-message-id-" + std::to_string(time(nullptr));

    Producer producer;
    ASSERT_EQ(ResultOk, client.createProducer(topic, producer));

    MessageId id;
    ASSERT_EQ(ResultOk, producer.send(MessageBuilder().setContent("msg").build(), id));

    Reader readerExclusive;
    ASSERT_EQ(ResultOk,
              client.createReader(topic, MessageId::latest(), ReaderConfiguration(), readerExclusive));

    Reader readerInclusive;
    ASSERT_EQ(ResultOk,
              client.createReader(topic, MessageId::latest(),
                                  ReaderConfiguration().setStartMessageIdInclusive(true), readerInclusive));

    Message msg;
    bool hasMsgAvaliable = false;
    readerInclusive.hasMessageAvailable(hasMsgAvaliable);
    ASSERT_TRUE(hasMsgAvaliable);
    ASSERT_EQ(ResultOk, readerInclusive.readNext(msg, 3000));
    ASSERT_EQ(ResultTimeout, readerExclusive.readNext(msg, 3000));

    readerExclusive.close();
    readerInclusive.close();
    producer.close();
```

### What did you expect to see?

The test should be passed.
The readerInclusive should be able to read the next message.

### What did you see instead?

The readerInclusive can't read the next message.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Samreay** [comment]
Hey @RobertIndie, any chance we can get a release of the C++ client with this fix in it soon? It's been a couple of months now and I'm conscious that the C++ needs to be released, then the python client updated, and then released, before I can use this fix.

**Comment by BewareMyPower** [comment]
I started the 2nd vote for the C++ client 3.5.0: https://lists.apache.org/thread/x9r3bcpmbnownd0twowpqwbqodgg7r8w

It has been delayed since I want to include the fix (https://github.com/apache/pulsar-client-cpp/pull/409) on another issue reported in the python client (https://github.com/apache/pulsar-client-python/issues/199).
