### ISSUE TITLE
How can I integrate pulsar client on macOS M1.

### ISSUE THREAD

**Issue by trinhtranduc** [apache/pulsar-client-cpp#430]
Hi,

I'm getting an error when trying to integrate the library into the Xcode project. Please see my screenshot!

<img width="1397" alt="Screenshot 2024-06-21 at 14 24 23" src="https://github.com/apache/pulsar-client-cpp/assets/55321757/10653782-e615-4ae3-a040-52e6defffdc6">
<img width="1401" alt="Screenshot 2024-06-21 at 14 24 36" src="https://github.com/apache/pulsar-client-cpp/assets/55321757/565e48d3-e69a-4f30-a908-6d0e030f91bd">

If there are any guidelines, please share them! Thank you!

**Comment by BewareMyPower** [comment]
The document [here](https://github.com/apache/pulsar-client-cpp?tab=readme-ov-file#how-to-install) is wrong, you should use `libpulsarwithdeps.a`, which bundles all 3rd party dependencies, or `libpulsar.dylib`.

If you only want to integrate it into your project, you can download the pre-built binaries directly from https://pulsar.apache.org/download/#pulsar-c-client. Or you can just install it via `brew install libpulsar`.

If you can use CMake, it's highly recommended to use vcpkg to add the dependency, see https://github.com/apache/pulsar-client-cpp/tree/main/vcpkg-example

**Comment by trinhtran-markany** [comment]
Thanks @BewareMyPower , I will try again.

**Comment by trinhtranduc** [comment]
@BewareMyPower Thanks, I gonna try again.

**Comment by trinhtranduc** [comment]
Hi @BewareMyPower I need only to integrate to my project so I decide to download pre-built binary, here is my step
**1. Download the package `macos-arm65.zip`**

<img width="718" alt="Screenshot 2024-06-24 at 10 46 20" src="https://github.com/apache/pulsar-client-cpp/assets/55321757/a73cdb9b-9eea-4657-a9ef-5235d3812559">

**2. Unzip this folder and copy them into project**

```
- pulsar/
      incude/
          pulsar/
      lib/
          libpulsarwithdeps.a
```

<img width="516" alt="Screenshot 2024-06-24 at 10 55 51" src="https://github.com/apache/pulsar-client-cpp/assets/55321757/1c008731-e76a-45b6-9e66-910bb35ca71a">


**3. Import library and try to initialize `Client` class**
```
#include <iostream>
#include <pulsar/Client.h>
#include <thread>

using namespace pulsar;

int main() {
    Client client("pulsar://localhost:6650");
}
```

Then i receive the error

`Undefined symbol: pulsar::Client::Client(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)`

Could you help to review above steps are correct?

**Comment by BewareMyPower** [comment]
Importing a dependency is not such trivial.

Generally, for a C++ project, you should configure
- The additional include directory
- The additional link directory
- The additional library to link

For a Xcode C++ project, you should first add the `include` and `lib` directories to the project. For example, I unzipped the file to the `/Users/xuyunze/pulsar-client-3.5.1` directory, then I would need to
- Add `/Users/xuyunze/pulsar-client-3.5.1/include` to **Header Search Paths**
- Add `/Users/xuyunze/pulsar-client-3.5.1/lib` to **Library Search Paths**

<img width="1031" alt="image" src="https://github.com/apache/pulsar-client-cpp/assets/18204803/31c101e8-56f5-492a-94b9-42159961ab8b">

Then, navigate to **Build Phases** - **Link Binary With Libraries** - `+` - **Add Files**, choose the `libpulsarwithdeps.a`

<img width="1016" alt="image" src="https://github.com/apache/pulsar-client-cpp/assets/18204803/063509aa-510e-4725-9cce-6b6ac403663d">

Now, you would be able to run the application successfully.

<img width="1199" alt="image" src="https://github.com/apache/pulsar-client-cpp/assets/18204803/7e34db6a-9729-4ead-b7b3-7b50594a630a">

**Comment by trinhtranduc** [comment]
Hi @BewareMyPower Thank you for your active help. I definitely set up both the **Header Search Paths** and **Library Search Paths**, but the error still occurs. 
I checked the downloaded package again and found out that I downloaded the wrong package: `macos-x86_64`. It should be `macos-arm64` for my Mac M1.
It's working now. Thank you a lot!
