### ISSUE TITLE
Add CI for build and tests

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar-client-cpp#5]
See:
- https://github.com/apache/pulsar/blob/master/.github/workflows/ci-cpp-build.yaml
- https://github.com/apache/pulsar/blob/0f53c790ff2e3051ebc80aa8d2c9253265725aeb/.github/workflows/pulsar-ci.yaml#L480-L482

**Comment by yaalsn** [comment]
@BewareMyPower @merlimat I'll add this workflow.

**Comment by BewareMyPower** [comment]
Thanks @yaalsn, I assigned it to you.

**Comment by merlimat** [comment]
Sorry, I didn't see this one. I added one PR to start addressing this: https://github.com/apache/pulsar-client-cpp/pull/14
